import pako from "pako";

/**
 * Compress JSONL content and encode to URL-safe base64 for sharing.
 * For files < 100KB compressed, embeds directly in URL hash.
 * For larger files, generates a standalone HTML file.
 */
export function compressForUrl(jsonlContent: string): string | null {
  try {
    const compressed = pako.deflate(new TextEncoder().encode(jsonlContent));
    const base64 = btoa(String.fromCharCode(...compressed));
    const urlSafe = base64
      .replace(/\+/g, "-")
      .replace(/\//g, "_")
      .replace(/=+$/, "");

    if (urlSafe.length > 100_000) return null;
    return urlSafe;
  } catch {
    return null;
  }
}

export function decompressFromUrl(encoded: string): string | null {
  try {
    const base64 = encoded.replace(/-/g, "+").replace(/_/g, "/");
    const padding = (4 - (base64.length % 4)) % 4;
    const padded = base64 + "=".repeat(padding);
    const binary = atob(padded);
    const bytes = new Uint8Array(binary.length);
    for (let i = 0; i < binary.length; i++) {
      bytes[i] = binary.charCodeAt(i);
    }
    const decompressed = pako.inflate(bytes);
    return new TextDecoder().decode(decompressed);
  } catch {
    return null;
  }
}

/**
 * Generate a standalone HTML file containing the viewer + embedded data.
 * This creates a self-contained replay that can be shared as a file.
 */
export function generateStandaloneHtml(
  jsonlContent: string,
  title: string
): string {
  const escapedContent = jsonlContent
    .replace(/\\/g, "\\\\")
    .replace(/`/g, "\\`")
    .replace(/\$/g, "\\$");

  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>${title} — AgentReel</title>
<style>
  * { margin: 0; padding: 0; box-sizing: border-box; }
  body { 
    font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
    background: #0a0a0f; color: #e8e8f0;
    display: flex; flex-direction: column; align-items: center;
    justify-content: center; min-height: 100vh; padding: 2rem;
  }
  h1 { font-size: 1.5rem; margin-bottom: 1rem; }
  .info { color: #a0a0b8; margin-bottom: 2rem; text-align: center; }
  a { color: #4e8cff; }
</style>
</head>
<body>
  <h1>▶ ${title}</h1>
  <p class="info">
    This replay was generated by <a href="https://agent-status.com/agentreel" target="_blank">AgentReel</a>.<br>
    Open the full viewer at <a href="https://agent-status.com/agentreel" target="_blank">agent-status.com/agentreel</a>
    and drag this file to view it interactively.
  </p>
  <script>
    window.__AGENTREEL_DATA__ = \`${escapedContent}\`;
  </script>
</body>
</html>`;
}
